import streamlit as st

# Page config
st.set_page_config(page_title="Background", page_icon="❤️", layout="wide")

# Custom CSS for modern look
st.markdown("""
    <style>
    .big-title {
        font-size: 3rem;
        font-weight: 700;
        margin-bottom: 0.5rem;
        line-height: 1.2;
        color: #ff4b4b;
    }
    .subtitle {
        font-size: 1.1rem;
        color: #555;
        margin-bottom: 1rem;
    }
    .feature-box {
        padding: 1.2rem;
        background: #f8f9fa;
        border-radius: 8px;
        border-left: 4px solid #ff4b4b;
        margin-bottom: 1rem;
    }
    </style>
""", unsafe_allow_html=True)

# Hero section
st.markdown('<h1 class="big-title">❤️ Project Background</h1>', unsafe_allow_html=True)
st.markdown('<p class="subtitle">Understand the motivation, objectives, and scope of the "Love Your Heart" app.</p>', unsafe_allow_html=True)

# Main content in two columns
col_left, col_right = st.columns([3, 2], gap="large")

with col_left:
    st.markdown("### Project Objective")
    st.write("""
    The goal of this project is to build an interactive web application that predicts an individual’s risk of heart disease
    based on self-reported lifestyle and health factors, such as age, BMI, smoking habits, diabetes, and physical activity.
    Users receive a personalized risk score generated by machine learning models, along with actionable lifestyle guidance
    provided through an AI-powered chatbot.
    """)

    st.markdown("### Target Audience")
    st.write("""
    Anyone interested in monitoring and improving cardiovascular health can use this tool. The dataset used covers adults
    from ages 18 to 80+, making the app applicable to a wide age range.
    """)

    st.markdown("### Key Features")
    st.write("""
    - **Personalized Risk Assessment:** Users provide lifestyle and health information to receive a machine learning risk score.
    - **AI Chatbot Guidance:** A chatbot offers tailored lifestyle advice to reduce cardiovascular risk.
    - **Explainable Insights:** Optional visualizations highlight which factors contribute most to heart risk.
    - **Privacy Focused:** All user data stays local; no sharing or storage on servers.
    """)

    st.markdown("### Tools and Technologies")
    st.write("""
    - **Programming & Libraries:** Python, pandas, scikit-learn, SQL, Streamlit
    - **AI & NLP:** LlamaIndex, HuggingFace Embeddings, Groq API
    - **Deployment:** Streamlit Cloud for interactive web interface
    """)

    st.markdown("### Data Sources")
    st.write("""
    The project uses publicly available health datasets to train predictive models:
    - [BRFSS 2020 Heart Disease Dataset](https://zenodo.org/records/15364962)
        """)
    # [Diabetes prediction dataset](https://www.kaggle.com/datasets/iammustafatz/diabetes-prediction-dataset/data)

    st.markdown("### Contact")
    st.write("""Developed by [Haripriya Raghunathan](https://www.linkedin.com/in/haripriya-raghunathan-a237732a9/) and [Nadine Jacobsen](https://www.linkedin.com/in/nadine-jacobsen/) as part of the WBS Data Science Bootcamp final project.
    \n For more details, visit the [GitHub repository](https://github.com/NadineJac/LoveYourHeart/tree/main)""")

with col_right:
    st.markdown("#### Why Use This Tool?")
    st.markdown("""
    <div class="feature-box">
        <strong>📊 Data-Driven Insights</strong><br>
        Leverages machine learning models trained on reliable datasets to provide personalized recommendations.
    </div>
    """, unsafe_allow_html=True)

    st.markdown("""
    <div class="feature-box">
        <strong>💡 Personalized Guidance</strong><br>
        AI-powered chatbot answers questions and provides actionable lifestyle tips tailored to each user.
    </div>
    """, unsafe_allow_html=True)

    st.markdown("""
    <div class="feature-box">
        <strong>⚡ Easy & Interactive</strong><br>
        Streamlit interface allows quick input and instant results with intuitive design.
    </div>
    """, unsafe_allow_html=True)

    st.markdown("""
    <div class="feature-box">
        <strong>🔒 Privacy First</strong><br>
        All user-provided information stays on the device; no cloud storage of personal data.
    </div>
    """, unsafe_allow_html=True)
